// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp4Kv8mrgsBHTILjc5mTigIPCLMbjYws8',
    appId: '1:860551664448:web:d5c6735a0541be231ae0a5',
    messagingSenderId: '860551664448',
    projectId: 'home-decor-477f3',
    authDomain: 'home-decor-477f3.firebaseapp.com',
    storageBucket: 'home-decor-477f3.firebasestorage.app',
    measurementId: 'G-VQ8XC7E4GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxyuSCBhSBx8BxARIRfw__jzpScnlYlO4',
    appId: '1:860551664448:android:f4d74d6381f88df41ae0a5',
    messagingSenderId: '860551664448',
    projectId: 'home-decor-477f3',
    storageBucket: 'home-decor-477f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0agQFlfBldkioiJFDjUYYy8SBD8uMAw',
    appId: '1:860551664448:ios:38fbcd8371d806241ae0a5',
    messagingSenderId: '860551664448',
    projectId: 'home-decor-477f3',
    storageBucket: 'home-decor-477f3.firebasestorage.app',
    iosBundleId: 'com.example.homeDecor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0agQFlfBldkioiJFDjUYYy8SBD8uMAw',
    appId: '1:860551664448:ios:38fbcd8371d806241ae0a5',
    messagingSenderId: '860551664448',
    projectId: 'home-decor-477f3',
    storageBucket: 'home-decor-477f3.firebasestorage.app',
    iosBundleId: 'com.example.homeDecor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp4Kv8mrgsBHTILjc5mTigIPCLMbjYws8',
    appId: '1:860551664448:web:60368225337289c11ae0a5',
    messagingSenderId: '860551664448',
    projectId: 'home-decor-477f3',
    authDomain: 'home-decor-477f3.firebaseapp.com',
    storageBucket: 'home-decor-477f3.firebasestorage.app',
    measurementId: 'G-MEZ4RGC6SD',
  );
}